name: Heizöl to MQTT
version: "0.1.5"
slug: heizoel_to_mqtt
description: Publish heating-oil price data to Home Assistant via MQTT Discovery
url: https://github.com/rockbaer2007/heizoel-to-mqtt
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
services:
  - mqtt:need
options:
  plz: ""
  amount: "3000"
  interval: 60
  esyActive: true
  deliveryTimes: ohne
  payment_type: ec
  prod: normal
  unloading_points: 1
  hose: fortyMetre
  short_vehicle: withTrailer
  hoDe: true
  hoAt: false
  log_response_details: false
schema:
  plz: str
  amount: str
  interval: int(30,1440)
  esyActive: bool
  deliveryTimes: "list(ohne|7:00 - 12:00 Uhr|12:00 - 17:00 Uhr|2 Wochentage (Express)|3 - 5 Wochentage (Mo.-Fr.)|6 - 10 Wochentage (Mo.-Fr.))"
  payment_type: list(ec|cash|guaranteedPayment|invoice|directDebit|inAdvance)
  prod: list(normal|premium|climateNeutralPremium|climateNeutralNormal|bio10|bio15|bio10Premium)
  unloading_points: int(1,9)
  hose: list(fortyMetre|sixtyMetre|eightyMetre)
  short_vehicle: list(withTrailer|withoutTrailer)
  hoDe: bool
  hoAt: bool
  log_response_details: bool
